import { LLMModels, LLMProvider } from "../enums/llm.js";
import type { ModelPricing, ModalityRates } from "./types.js";

export type ModelStatus = "live" | "deprecated" | "retired";

export type ModelFamily = "gpt" | "claude" | "gemini" | "grok" | "glm";

export type ByokProvider = "anthropic" | "openai" | "openrouter";

/** Reasoning settings the voice worker can send to keep replies fast. */
export type VoiceReasoning = "none" | "minimal";

export interface ModelCapabilities {
  thinking: boolean;
  adaptiveThinking: boolean;
  vision: boolean;
  customTemperature: boolean;
  nativeAudioVideo: boolean;
}

export interface ModelDefinition {
  id: LLMModels;
  label: string;
  provider: LLMProvider;
  family: ModelFamily;
  status: ModelStatus;
  replacedBy?: LLMModels;
  offeredInChat: boolean;
  chatOrder?: number;
  /** Whether voice agent model pickers offer this model. */
  offeredInVoice: boolean;
  /** Lowest reasoning setting the voice worker sends for this model, so replies start fast. */
  voiceReasoning?: VoiceReasoning;
  premium: boolean;
  pricing: ModelPricing;
  modality?: ModalityRates;
  maxOutputTokens: number;
  capabilities: ModelCapabilities;
  byokProvider?: ByokProvider;
  openRouterSlug?: string;
}

export const MAX_OUTPUT_TOKENS = 14_500;

export const GEMINI_MAX_OUTPUT_TOKENS = 49_152;

export const OPENROUTER_MAX_OUTPUT_TOKENS = 16_384;

const NO_CAPS: ModelCapabilities = {
  thinking: false,
  adaptiveThinking: false,
  vision: false,
  customTemperature: true,
  nativeAudioVideo: false,
};
const GPT_LEGACY: ModelCapabilities = { ...NO_CAPS };
const GPT_5: ModelCapabilities = { ...NO_CAPS, thinking: true, customTemperature: false };
const CLAUDE_LEGACY: ModelCapabilities = { ...NO_CAPS };
const CLAUDE_4: ModelCapabilities = { ...NO_CAPS, thinking: true };
const CLAUDE_ADAPTIVE: ModelCapabilities = { ...NO_CAPS, thinking: true, adaptiveThinking: true, customTemperature: false };
const GEMINI_LEGACY: ModelCapabilities = { ...NO_CAPS, nativeAudioVideo: true };
const GEMINI_THINKING: ModelCapabilities = { ...NO_CAPS, thinking: true, nativeAudioVideo: true };

export const MODEL_REGISTRY: readonly ModelDefinition[] = [
  {
    id: LLMModels.GPT_3_5,
    label: "GPT-3.5",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "retired",
    replacedBy: LLMModels.GPT_5_4_MINI_2026_03_17,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: { inputPerMillion: 0.5, outputPerMillion: 1.5, provider: LLMProvider.OPENAI },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_LEGACY,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_3_5_TURBO_16K,
    label: "GPT-3.5 Turbo 16k",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "retired",
    replacedBy: LLMModels.GPT_5_4_MINI_2026_03_17,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: { inputPerMillion: 3, outputPerMillion: 4, provider: LLMProvider.OPENAI },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_LEGACY,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_3_5_TURBO_0125,
    label: "GPT-3.5 Turbo",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "retired",
    replacedBy: LLMModels.GPT_5_4_MINI_2026_03_17,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: { inputPerMillion: 0.5, outputPerMillion: 1.5, provider: LLMProvider.OPENAI },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_LEGACY,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_4,
    label: "GPT-4",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "retired",
    replacedBy: LLMModels.GPT_5_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: { inputPerMillion: 30, outputPerMillion: 60, provider: LLMProvider.OPENAI },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_LEGACY,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_4_1106_PREVIEW,
    label: "GPT-4 Turbo Preview",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "retired",
    replacedBy: LLMModels.GPT_5_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: { inputPerMillion: 10, outputPerMillion: 30, provider: LLMProvider.OPENAI },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_LEGACY,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_4_TURBO,
    label: "GPT-4 Turbo",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "retired",
    replacedBy: LLMModels.GPT_5_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: { inputPerMillion: 10, outputPerMillion: 30, provider: LLMProvider.OPENAI },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_LEGACY,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_4_O_2024_05_13,
    label: "GPT-4o (2024-05-13)",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "retired",
    replacedBy: LLMModels.GPT_5_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: { inputPerMillion: 5, outputPerMillion: 15, provider: LLMProvider.OPENAI },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_LEGACY,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_4O,
    label: "GPT-4o",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "deprecated",
    replacedBy: LLMModels.GPT_5_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 2.5,
      outputPerMillion: 10,
      cachedInputPerMillion: 1.25,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_LEGACY,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_4O_MINI,
    label: "GPT-4o mini",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "deprecated",
    replacedBy: LLMModels.GPT_5_4_MINI_2026_03_17,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: {
      inputPerMillion: 0.15,
      outputPerMillion: 0.6,
      cachedInputPerMillion: 0.075,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_LEGACY,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_4_O_2024_08_06,
    label: "GPT-4o (2024-08-06)",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "deprecated",
    replacedBy: LLMModels.GPT_5_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 2.5,
      outputPerMillion: 10,
      cachedInputPerMillion: 1.25,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_LEGACY,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_4_MINI_2024_07_18,
    label: "GPT-4o mini (2024-07-18)",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "deprecated",
    replacedBy: LLMModels.GPT_5_4_MINI_2026_03_17,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: {
      inputPerMillion: 0.15,
      outputPerMillion: 0.6,
      cachedInputPerMillion: 0.075,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_LEGACY,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_4_1_2025_04_14,
    label: "GPT-4.1",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "deprecated",
    replacedBy: LLMModels.GPT_5_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 2,
      outputPerMillion: 8,
      cachedInputPerMillion: 0.5,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_LEGACY,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_5_1_2025_11_13,
    label: "GPT-5.1",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "deprecated",
    replacedBy: LLMModels.GPT_5_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 1.25,
      outputPerMillion: 10,
      cachedInputPerMillion: 0.125,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_5,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_5_2,
    label: "GPT-5.2",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "deprecated",
    replacedBy: LLMModels.GPT_5_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 1.75,
      outputPerMillion: 14,
      cachedInputPerMillion: 0.175,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_5,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_5_4,
    label: "GPT-5.4",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "deprecated",
    replacedBy: LLMModels.GPT_5_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 2.5,
      outputPerMillion: 15,
      cachedInputPerMillion: 0.25,
      longContextThresholdTokens: 272000,
      inputPerMillionLong: 5,
      outputPerMillionLong: 22.5,
      cachedInputPerMillionLong: 0.5,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_5,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_5_4_MINI,
    label: "GPT-5.4 mini",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "deprecated",
    replacedBy: LLMModels.GPT_5_4_MINI_2026_03_17,
    offeredInChat: false,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 0.75,
      outputPerMillion: 4.5,
      cachedInputPerMillion: 0.075,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_5,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_5_4_NANO,
    label: "GPT-5.4 nano",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "deprecated",
    replacedBy: LLMModels.GPT_5_4_MINI_2026_03_17,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: {
      inputPerMillion: 0.2,
      outputPerMillion: 1.25,
      cachedInputPerMillion: 0.02,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_5,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_5_5_THINKING,
    label: "GPT-5.5 Thinking",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "deprecated",
    replacedBy: LLMModels.GPT_5_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 5,
      outputPerMillion: 30,
      cachedInputPerMillion: 0.5,
      longContextThresholdTokens: 272000,
      inputPerMillionLong: 10,
      outputPerMillionLong: 45,
      cachedInputPerMillionLong: 1,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_5,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_5_6_LUNA,
    label: "GPT-5.6 Luna",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "deprecated",
    replacedBy: LLMModels.GPT_5_4_MINI_2026_03_17,
    offeredInChat: false,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 1,
      outputPerMillion: 6,
      cachedInputPerMillion: 0.1,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_5,
    byokProvider: "openai",
  },
  {
    id: LLMModels.GPT_5_4_MINI_2026_03_17,
    label: "GPT-5.4 mini",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "live",
    offeredInChat: true,
    chatOrder: 7,
    offeredInVoice: true,
    voiceReasoning: "none",
    premium: true,
    pricing: {
      inputPerMillion: 0.75,
      outputPerMillion: 4.5,
      cachedInputPerMillion: 0.075,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_5,
    byokProvider: "openai",
    openRouterSlug: "openai/gpt-5.4-mini",
  },
  {
    id: LLMModels.GPT_5_5,
    label: "GPT-5.5",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "live",
    offeredInChat: true,
    chatOrder: 6,
    offeredInVoice: true,
    voiceReasoning: "none",
    premium: true,
    pricing: {
      inputPerMillion: 5,
      outputPerMillion: 30,
      cachedInputPerMillion: 0.5,
      longContextThresholdTokens: 272000,
      inputPerMillionLong: 10,
      outputPerMillionLong: 45,
      cachedInputPerMillionLong: 1,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_5,
    byokProvider: "openai",
    openRouterSlug: "openai/gpt-5.5",
  },
  {
    id: LLMModels.GPT_5_6_SOL,
    label: "GPT-5.6 Sol",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "live",
    offeredInChat: true,
    chatOrder: 5,
    offeredInVoice: true,
    voiceReasoning: "none",
    premium: true,
    pricing: {
      inputPerMillion: 5,
      outputPerMillion: 30,
      cachedInputPerMillion: 0.5,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_5,
    byokProvider: "openai",
    openRouterSlug: "openai/gpt-5.6-sol",
  },
  {
    id: LLMModels.GPT_5_6_TERRA,
    label: "GPT-5.6 Terra",
    provider: LLMProvider.OPENAI,
    family: "gpt",
    status: "live",
    offeredInChat: true,
    chatOrder: 4,
    offeredInVoice: true,
    voiceReasoning: "none",
    premium: true,
    pricing: {
      inputPerMillion: 2.5,
      outputPerMillion: 15,
      cachedInputPerMillion: 0.25,
      provider: LLMProvider.OPENAI,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GPT_5,
    byokProvider: "openai",
    openRouterSlug: "openai/gpt-5.6-terra",
  },

  {
    id: LLMModels.CLAUDE_2,
    label: "Claude 2",
    provider: LLMProvider.ANTHROPIC,
    family: "claude",
    status: "retired",
    replacedBy: LLMModels.CLAUDE_SONNET_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: { inputPerMillion: 8, outputPerMillion: 24, provider: LLMProvider.ANTHROPIC },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: CLAUDE_LEGACY,
    byokProvider: "anthropic",
  },
  {
    id: LLMModels.CLAUDE_3_5_SONNET,
    label: "Claude 3.5 Sonnet",
    provider: LLMProvider.ANTHROPIC,
    family: "claude",
    status: "retired",
    replacedBy: LLMModels.CLAUDE_SONNET_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: {
      inputPerMillion: 3,
      outputPerMillion: 15,
      cachedInputPerMillion: 0.3,
      provider: LLMProvider.ANTHROPIC,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: CLAUDE_LEGACY,
    byokProvider: "anthropic",
  },
  {
    id: LLMModels.CLAUDE_3_5_SONNET_20241022,
    label: "Claude 3.5 Sonnet (2024-10-22)",
    provider: LLMProvider.ANTHROPIC,
    family: "claude",
    status: "retired",
    replacedBy: LLMModels.CLAUDE_SONNET_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: {
      inputPerMillion: 3,
      outputPerMillion: 15,
      cachedInputPerMillion: 0.3,
      provider: LLMProvider.ANTHROPIC,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: CLAUDE_LEGACY,
    byokProvider: "anthropic",
  },
  {
    id: LLMModels.CLAUDE_3_7_SONNET_LATEST,
    label: "Claude 3.7 Sonnet",
    provider: LLMProvider.ANTHROPIC,
    family: "claude",
    status: "retired",
    replacedBy: LLMModels.CLAUDE_SONNET_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: {
      inputPerMillion: 3,
      outputPerMillion: 15,
      cachedInputPerMillion: 0.3,
      provider: LLMProvider.ANTHROPIC,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: CLAUDE_LEGACY,
    byokProvider: "anthropic",
  },
  {
    id: LLMModels.CLAUDE_HAIKU_4_5,
    label: "Claude Haiku 4.5",
    provider: LLMProvider.ANTHROPIC,
    family: "claude",
    status: "deprecated",
    replacedBy: LLMModels.CLAUDE_SONNET_5,
    offeredInChat: false,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 1,
      outputPerMillion: 5,
      cachedInputPerMillion: 0.1,
      provider: LLMProvider.ANTHROPIC,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: { ...CLAUDE_4, thinking: false },
    byokProvider: "anthropic",
  },
  {
    id: LLMModels.CLAUDE_SONNET_4_6,
    label: "Claude Sonnet 4.6",
    provider: LLMProvider.ANTHROPIC,
    family: "claude",
    status: "live",
    offeredInChat: true,
    chatOrder: 10,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 3,
      outputPerMillion: 15,
      cachedInputPerMillion: 0.3,
      provider: LLMProvider.ANTHROPIC,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: CLAUDE_4,
    byokProvider: "anthropic",
    openRouterSlug: "anthropic/claude-sonnet-4.6",
  },
  {
    id: LLMModels.CLAUDE_SONNET_5,
    label: "Claude Sonnet 5",
    provider: LLMProvider.ANTHROPIC,
    family: "claude",
    status: "live",
    offeredInChat: true,
    chatOrder: 8,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 3,
      outputPerMillion: 15,
      cachedInputPerMillion: 0.3,
      provider: LLMProvider.ANTHROPIC,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: CLAUDE_ADAPTIVE,
    byokProvider: "anthropic",
    openRouterSlug: "anthropic/claude-sonnet-5",
  },
  {
    id: LLMModels.CLAUDE_OPUS_4_8,
    label: "Claude Opus 4.8",
    provider: LLMProvider.ANTHROPIC,
    family: "claude",
    status: "live",
    offeredInChat: true,
    chatOrder: 9,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 5,
      outputPerMillion: 25,
      cachedInputPerMillion: 0.5,
      provider: LLMProvider.ANTHROPIC,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: CLAUDE_ADAPTIVE,
    byokProvider: "anthropic",
    openRouterSlug: "anthropic/claude-opus-4.8",
  },

  {
    id: LLMModels.GEMINI_1_5_PRO,
    label: "Gemini 1.5 Pro",
    provider: LLMProvider.GOOGLE,
    family: "gemini",
    status: "retired",
    replacedBy: LLMModels.GEMINI_3_8_FLASH,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: { inputPerMillion: 1.25, outputPerMillion: 5, provider: LLMProvider.GOOGLE },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GEMINI_LEGACY,
  },
  {
    id: LLMModels.GEMINI_1_5_FLASH,
    label: "Gemini 1.5 Flash",
    provider: LLMProvider.GOOGLE,
    family: "gemini",
    status: "retired",
    replacedBy: LLMModels.GEMINI_3_7_FLASH,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: {
      inputPerMillion: 0.075,
      outputPerMillion: 0.3,
      cachedInputPerMillion: 0.01875,
      provider: LLMProvider.GOOGLE,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GEMINI_LEGACY,
  },
  {
    id: LLMModels.GEMINI_2_0_FLASH,
    label: "Gemini 2.0 Flash",
    provider: LLMProvider.GOOGLE,
    family: "gemini",
    status: "retired",
    replacedBy: LLMModels.GEMINI_3_7_FLASH,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: {
      inputPerMillion: 0.1,
      outputPerMillion: 0.4,
      cachedInputPerMillion: 0.025,
      provider: LLMProvider.GOOGLE,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GEMINI_LEGACY,
  },
  {
    id: LLMModels.GEMINI_2_5_FLASH,
    label: "Gemini 2.5 Flash",
    provider: LLMProvider.GOOGLE,
    family: "gemini",
    status: "deprecated",
    replacedBy: LLMModels.GEMINI_3_7_FLASH,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: {
      inputPerMillion: 0.3,
      outputPerMillion: 2.5,
      cachedInputPerMillion: 0.03,
      provider: LLMProvider.GOOGLE,
    },
    modality: { audioPerMillion: 1.0, videoPerMillion: 0.3 },
    maxOutputTokens: GEMINI_MAX_OUTPUT_TOKENS,
    capabilities: GEMINI_THINKING,
  },
  {
    id: LLMModels.GEMINI_2_5_PRO,
    label: "Gemini 2.5 Pro",
    provider: LLMProvider.GOOGLE,
    family: "gemini",
    status: "deprecated",
    replacedBy: LLMModels.GEMINI_3_8_FLASH,
    offeredInChat: false,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 1.25,
      outputPerMillion: 10,
      longContextThresholdTokens: 200000,
      inputPerMillionLong: 2.5,
      outputPerMillionLong: 15,
      provider: LLMProvider.GOOGLE,
    },
    modality: { audioPerMillion: 1.25, videoPerMillion: 1.25 },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GEMINI_THINKING,
  },
  {
    id: LLMModels.GEMINI_2_5_FLASH_LITE,
    label: "Gemini 2.5 Flash Lite",
    provider: LLMProvider.GOOGLE,
    family: "gemini",
    status: "deprecated",
    replacedBy: LLMModels.GEMINI_3_7_FLASH,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: {
      inputPerMillion: 0.1,
      outputPerMillion: 0.4,
      cachedInputPerMillion: 0.01,
      provider: LLMProvider.GOOGLE,
    },
    modality: { audioPerMillion: 0.3, videoPerMillion: 0.1 },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GEMINI_THINKING,
  },
  {
    id: LLMModels.GEMINI_3_1_FLASH_LITE,
    label: "Gemini 3.1 Flash Lite",
    provider: LLMProvider.GOOGLE,
    family: "gemini",
    status: "deprecated",
    replacedBy: LLMModels.GEMINI_3_7_FLASH,
    offeredInChat: false,
    offeredInVoice: false,
    premium: false,
    pricing: { inputPerMillion: 0.25, outputPerMillion: 1.5, provider: LLMProvider.GOOGLE },
    modality: { audioPerMillion: 0.5, videoPerMillion: 0.25 },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GEMINI_THINKING,
  },
  {
    id: LLMModels.GEMINI_3_1_PRO_PREVIEW,
    label: "Gemini 3.1 Pro",
    provider: LLMProvider.GOOGLE,
    family: "gemini",
    status: "deprecated",
    replacedBy: LLMModels.GEMINI_3_8_FLASH,
    offeredInChat: false,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 2,
      outputPerMillion: 12,
      longContextThresholdTokens: 200000,
      inputPerMillionLong: 4,
      outputPerMillionLong: 18,
      provider: LLMProvider.GOOGLE,
    },
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    capabilities: GEMINI_THINKING,
  },
  {
    id: LLMModels.GEMINI_3_FLASH_PREVIEW,
    label: "Gemini 3 Flash",
    provider: LLMProvider.GOOGLE,
    family: "gemini",
    status: "live",
    offeredInChat: true,
    chatOrder: 1,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 0.5,
      outputPerMillion: 3,
      cachedInputPerMillion: 0.05,
      provider: LLMProvider.GOOGLE,
    },
    modality: { audioPerMillion: 1.0, videoPerMillion: 0.5 },
    maxOutputTokens: GEMINI_MAX_OUTPUT_TOKENS,
    capabilities: GEMINI_THINKING,
    openRouterSlug: "google/gemini-3-flash-preview",
  },
  {
    id: LLMModels.GEMINI_3_5_FLASH,
    label: "Gemini 3.5 Flash",
    provider: LLMProvider.GOOGLE,
    family: "gemini",
    status: "live",
    offeredInChat: true,
    chatOrder: 2,
    offeredInVoice: true,
    voiceReasoning: "minimal",
    premium: true,
    pricing: {
      inputPerMillion: 1.5,
      outputPerMillion: 9,
      cachedInputPerMillion: 0.15,
      provider: LLMProvider.GOOGLE,
    },
    modality: { audioPerMillion: 3.0, videoPerMillion: 1.5 },
    maxOutputTokens: GEMINI_MAX_OUTPUT_TOKENS,
    capabilities: GEMINI_THINKING,
    openRouterSlug: "google/gemini-3.5-flash",
  },
  {
    id: LLMModels.GEMINI_3_7_FLASH,
    label: "Gemini 3.7 Flash",
    provider: LLMProvider.GOOGLE,
    family: "gemini",
    status: "live",
    offeredInChat: true,
    chatOrder: 0,
    offeredInVoice: false,
    premium: false,
    pricing: {
      inputPerMillion: 0.75,
      outputPerMillion: 3.75,
      cachedInputPerMillion: 0.075,
      provider: LLMProvider.GOOGLE,
    },
    modality: { audioPerMillion: 1.5, videoPerMillion: 0.75 },
    maxOutputTokens: GEMINI_MAX_OUTPUT_TOKENS,
    capabilities: GEMINI_THINKING,
    openRouterSlug: "google/gemini-3.7-flash",
  },
  {
    id: LLMModels.GEMINI_3_8_FLASH,
    label: "Gemini 3.8 Flash",
    provider: LLMProvider.GOOGLE,
    family: "gemini",
    status: "live",
    offeredInChat: true,
    chatOrder: 3,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 0.75,
      outputPerMillion: 3.75,
      cachedInputPerMillion: 0.075,
      provider: LLMProvider.GOOGLE,
    },
    modality: { audioPerMillion: 1.5, videoPerMillion: 0.75 },
    maxOutputTokens: GEMINI_MAX_OUTPUT_TOKENS,
    capabilities: GEMINI_THINKING,
    openRouterSlug: "google/gemini-3.8-flash",
  },

  {
    id: LLMModels.GROK_4_5,
    label: "Grok 4.5",
    provider: LLMProvider.OPENROUTER,
    family: "grok",
    status: "live",
    offeredInChat: true,
    chatOrder: 11,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 2.2,
      outputPerMillion: 6.6,
      cachedInputPerMillion: 0.22,
      provider: LLMProvider.OPENROUTER,
    },
    maxOutputTokens: OPENROUTER_MAX_OUTPUT_TOKENS,
    capabilities: { ...NO_CAPS, thinking: true, vision: true },
    byokProvider: "openrouter",
  },
  {
    id: LLMModels.GLM_5_2,
    label: "GLM 5.2",
    provider: LLMProvider.OPENROUTER,
    family: "glm",
    status: "live",
    offeredInChat: true,
    chatOrder: 12,
    offeredInVoice: false,
    premium: true,
    pricing: {
      inputPerMillion: 1.023,
      outputPerMillion: 3.3,
      cachedInputPerMillion: 0.1023,
      provider: LLMProvider.OPENROUTER,
    },
    maxOutputTokens: OPENROUTER_MAX_OUTPUT_TOKENS,
    capabilities: { ...NO_CAPS, thinking: true },
    byokProvider: "openrouter",
  },
] as const;

export const OPENAI_DEFAULT_MODEL = LLMModels.GPT_5_5;
export const CLAUDE_DEFAULT_MODEL = LLMModels.CLAUDE_SONNET_5;
export const GEMINI_DEFAULT_MODEL = LLMModels.GEMINI_3_7_FLASH;
export const OPENROUTER_DEFAULT_MODEL = LLMModels.GROK_4_5;

export const MEDIA_ROUTED_MODEL = GEMINI_DEFAULT_MODEL;

export const FREE_TIER_MODEL = LLMModels.GEMINI_3_7_FLASH;

export const DEFAULT_MODELS = {
  OPENAI_DEFAULT_MODEL,
  CLAUDE_DEFAULT_MODEL,
  GEMINI_DEFAULT_MODEL,
  OPENROUTER_DEFAULT_MODEL,
  MEDIA_ROUTED_MODEL,
  FREE_TIER_MODEL,
} as const;

const BY_ID = new Map<string, ModelDefinition>(MODEL_REGISTRY.map((m) => [m.id.toLowerCase(), m]));

export function getModel(modelId: string): ModelDefinition | undefined {
  return BY_ID.get(modelId.toLowerCase());
}

export function modelsByStatus(status: ModelStatus): ModelDefinition[] {
  return MODEL_REGISTRY.filter((m) => m.status === status);
}

export function offeredChatModels(): ModelDefinition[] {
  return MODEL_REGISTRY.filter((m) => m.status === "live" && m.offeredInChat).sort(
    (a, b) => (a.chatOrder ?? Infinity) - (b.chatOrder ?? Infinity),
  );
}

export function resolveModelId(modelId: string): LLMModels | undefined {
  let current = getModel(modelId);
  const seen = new Set<string>();
  while (current && current.status === "retired" && current.replacedBy) {
    if (seen.has(current.id)) return undefined;
    seen.add(current.id);
    current = getModel(current.replacedBy);
  }
  return current?.id;
}

export function requiresMediaCapableModel(
  modelId: string | undefined,
  modalities: ReadonlySet<"audio" | "video" | "image">,
): boolean {
  if (!modalities.has("audio") && !modalities.has("video")) return false;
  return !(modelId && getModel(modelId)?.capabilities.nativeAudioVideo);
}
