export enum ExportFormatType {
  CSV = 'csv',
  CSV_INSIGHTS = 'csv-insights',
  CSV_TRANSCRIPT = 'csv-transcript',
  CSV_TRANSCRIPT_WITH_SENTIMENT = 'csv-transcript-sentiment',
  CSV_TEXT_WITH_SENTIMENT = 'csv-text-sentiment',
  DOCX = 'docx',
  HTML = 'html',
  JSON = 'json',
  PDF = 'pdf',
  SOURCEFILE = 'sourceFile',
  SRT = 'srt',
  TTML = 'ttml',
  TXT = 'txt',
  VTT = 'vtt',
  MP4 = 'mp4',
}
