export enum NotificationType {
  CLIP = 'clip',
  AUDIO = 'audio',
  ACCOUNT = 'account',
  AUTOMATION = 'automation',
  EMBED = 'embed',
  INTEGRATION = 'integration',
  MAGIC_PROMPT = 'magic prompt',
  MEDIA = 'media',
  PAYMENT = 'payment',
  PRESENTATION = 'presentation',
  RECORDER = 'recorder',
  SURVEY = 'survey',
  SUBSCRIPTION = 'subscription',
  TEAM = 'team',
  TEXT = 'text',
  TRANSCRIPTION = 'transcription',
  TRANSLATE = 'translate',
  VIDEO = 'video',
  ZAPIER = 'zapier',
  MEETING_ASSISTANT = 'meeting assistant',
  GOOGLE_CALENDAR = 'google calendar',
  OUTLOOK_CALENDAR = 'outlook calendar',
  AUTO_RELOAD = 'auto reload',
  FOLDER = 'folder',
  FIELDS = 'fields',
  ASSISTANT_TEMPLATE = 'assistant template',
}

export enum NotificationAction {
  ANALYZED = 'analyzed',
  CREATED = 'created',
  CREDIT = 'credit',
  DEBIT = 'debit',
  DELETED = 'deleted',
  EXPORT = 'export',
  PAID = 'paid',
  UPDATED = 'updated',
  UPLOADED = 'uploaded',
  ERROR = 'error',
  FAILED = 'failed',
  CLONED = 'cloned',
}
