export enum NotificationType {
  Clip = 'clip',
  Audio = 'audio',
  Account = 'account',
  Automation = 'automation',
  Embed = 'embed',
  Integration = 'integration',
  MagicPrompt = 'magic prompt',
  Media = 'media',
  Payment = 'payment',
  Presentation = 'presentation',
  Recorder = 'recorder',
  Survey = 'survey',
  Subscription = 'subscription',
  Team = 'team',
  Text = 'text',
  Transcription = 'transcription',
  Translate = 'translate',
  Video = 'video',
  Zapier = 'zapier',
  MeetingAssistant = 'meeting assistant',
  GoogleCalendar = 'google calendar',
}

export enum NotificationAction {
  Analyzed = 'analyzed',
  Created = 'created',
  Credit = 'credit',
  Debit = 'debit',
  Deleted = 'deleted',
  Export = 'export',
  Paid = 'paid',
  Updated = 'updated',
  Uploaded = 'uploaded',
  Error = 'error',
  Failed = 'failed',
  Cloned = 'cloned',
}
