export enum TranscriptionEngine {
  Azure = 'azure',
  Assembly = 'assembly',
  Deepgram = 'deepgram',
  Aws = 'aws',
}

export enum TranscriptionJobState {
  Initiate = 'initiate',
  PendingPayment = 'pendingPayment',
  InQueue = 'inQueue',
  PendingEdition = 'pendingEdition',
  PendingQAReview = 'pendingQAReview',
  PendingUserReview = 'pendingUserReview',
  Complete = 'complete',
  Failed = 'failed',
}

export enum TranscriptionJobRevisionState {
  Approved = 'approved',
  BeingEdited = 'beingEdited',
  BeingQAReviewed = 'beingQAReviewed',
  PendingQAReview = 'pendingQAReview',
  PendingUserReview = 'pendingUserReview',
  Rejected = 'rejected',
}

export const TranscriptionLanguages = {
  'en-US': 'English (US)',
  'en-AU': 'English (Australia)',
  'en-GB': 'English (British)',
  'en-IN': 'English (Indian)',
  'en-IE': 'English (Irish)',
  'en-NZ': 'English (New Zealand)',
  'en-AB': 'English (Scottish)',
  'en-ZA': 'English (South African)',
  'fr-FR': 'French',
  'fr-CA': 'French (Canada)',
  'es-ES': 'Spanish',
  'es-MX': 'Spanish (Mexico)',
  'af-ZA': 'Afrikaans',
  'hy-AM': 'Armenian',
  'ar-AE': 'Arabic (U.A.E.)',
  'ar-BH': 'Arabic (Bahrain)',
  'ar-EG': 'Arabic (Egypt)',
  'ar-IL': 'Arabic (Israel)',
  'ar-IQ': 'Arabic (Iraq)',
  'ar-JO': 'Arabic (Jordan)',
  'ar-KW': 'Arabic (Kuwait)',
  'ar-LB': 'Arabic (Lebanon)',
  'ar-OM': 'Arabic (Oman)',
  'ar-PS': 'Arabic (Palestinian Authority)',
  'ar-QA': 'Arabic (Qatar)',
  'ar-SA': 'Arabic (Saudi Arabia)',
  'ar-SY': 'Arabic Syrian Arab Republic',
  'bg-BG': 'Bulgarian',
  'ca-ES': 'Catalan',
  'hr-HR': 'Croatian',
  'cs-CZ': 'Czech',
  'da-DK': 'Danish',
  'nl-NL': 'Dutch',
  'et-EE': 'Estonian',
  'fa-IR': 'Farsi',
  'fi-FI': 'Finnish',
  'de-CH': 'German (Swiss)',
  'de-DE': 'German',
  'el-GR': 'Greek',
  'gu-IN': 'Gujarati',
  'he-IL': 'Hebrew',
  'hi-IN': 'Hindi',
  'hu-HU': 'Hungarian',
  'is-IS': 'Icelandic',
  'ga-IE': 'Irish',
  'id-ID': 'Indonesian',
  'it-IT': 'Italian',
  'ja-JP': 'Japanese',
  'kn-IN': 'Kannada',
  'ko-KR': 'Korean',
  'lt-LT': 'Lithuanian',
  'lv-LV': 'Latvian',
  'ml-IN': 'Malayalam',
  'ms-MY': 'Malay',
  'nb-NO': 'Norwegian',
  'pl-PL': 'Polish',
  'pt-BR': 'Portuguese (Brazilian)',
  'pt-PT': 'Portuguese (Portugal)',
  'ro-RO': 'Romanian',
  'ru-RU': 'Russian',
  'sk-SK': 'Slovak',
  'sl-SI': 'Slovenian',
  'sv-SE': 'Swedish',
  'ta-IN': 'Tamil',
  'te-IN': 'Telugu',
  'th-TH': 'Thai',
  'tr-TR': 'Turkish',
  'uk-UA': 'Ukrainian',
  'vi-VN': 'Vietnamese',
  'zh-CN': 'Chinese (Simplified)',
  'zh-TW': 'Chinese (Traditional)',
} as const;
